//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adaos.Shell.Executer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class help : global::System.Configuration.ApplicationSettingsBase {
        
        private static help defaultInstance = ((help)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new help())));
        
        public static help Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usage: math.multiplication <double | int | integer> [number...]\r\n\r\nExample:\r\n    " +
            "math.multiplication int 1 2 3")]
        public string MathMultiplication {
            get {
                return ((string)(this["MathMultiplication"]));
            }
            set {
                this["MathMultiplication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usage: math.sum <double | int | integer> [number...]\r\n\r\nExample:\r\n    math.sum do" +
            "uble 3.5 4.2")]
        public string MathSum {
            get {
                return ((string)(this["MathSum"]));
            }
            set {
                this["MathSum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usage: math.rand [options...] [number] [number]\r\n\r\nOptions:\r\n    width [number]  " +
            "                                  default: 0\r\n    mode [chars | double | int | i" +
            "nteger]    default: int")]
        public string MathRandom {
            get {
                return ((string)(this["MathRandom"]));
            }
            set {
                this["MathRandom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usage: math.sqrt [number...]")]
        public string MathSqrt {
            get {
                return ((string)(this["MathSqrt"]));
            }
            set {
                this["MathSqrt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usage: math.pow [base] [exponent]\r\n\r\nBase: [number]\r\n\r\nExponent: [number]")]
        public string MathPow {
            get {
                return ((string)(this["MathPow"]));
            }
            set {
                this["MathPow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usage: system.redo [option...]\r\n\r\nOptions:\r\n    back [number]    default: 1\r\n    " +
            "limit [number]    default: 1\r\n    times [number]    default: 1")]
        public string SystemRedo {
            get {
                return ((string)(this["SystemRedo"]));
            }
            set {
                this["SystemRedo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usage: system.echo [args...]\r\n\r\nExample:\r\n    system.echo \"In here the number    " +
            "  of space count     .\" not out     here\r\n\r\nResult:\r\n    In here the number     " +
            " of space count     . not out here")]
        public string SystemEcho {
            get {
                return ((string)(this["SystemEcho"]));
            }
            set {
                this["SystemEcho"] = value;
            }
        }
    }
}
